DROP TABLE IF EXISTS Log_Entry;
DROP TABLE IF EXISTS Exercise_Workout_Target;
DROP TABLE IF EXISTS Exercise_Workout_Junction;
DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS Exercise;
DROP TABLE IF EXISTS Workout;
DROP TABLE IF EXISTS Workout_Type;
DROP TABLE IF EXISTS Users;