// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Exercise struct {
	ID             int32  `json:"id"`
	ExerciseName   string `json:"exercise_name"`
	ExerciseTypeID string `json:"exercise_type_id"`
	UserID         int32  `json:"user_id"`
}

type ExerciseWorkoutJunction struct {
	ID         int32 `json:"id"`
	ExerciseID int32 `json:"exercise_id"`
	WorkoutID  int32 `json:"workout_id"`
	UserID     int32 `json:"user_id"`
}

type ExerciseWorkoutTarget struct {
	ID         int32 `json:"id"`
	JunctionID int32 `json:"junction_id"`
	SetNumber  int32 `json:"set_number"`
	MinReps    int32 `json:"min_reps"`
	MaxReps    int32 `json:"max_reps"`
}

type Log struct {
	ID        int32     `json:"id"`
	WorkoutID int32     `json:"workout_id"`
	Dateof    time.Time `json:"dateof"`
	UserID    int32     `json:"user_id"`
}

type LogEntry struct {
	ID           int32        `json:"id"`
	LogID        int32        `json:"log_id"`
	JunctionID   int32        `json:"junction_id"`
	SetNumber    int32        `json:"set_number"`
	Weight       int32        `json:"weight"`
	Reps         int32        `json:"reps"`
	TimeRecorded sql.NullTime `json:"time_recorded"`
}

type User struct {
	ID          int32        `json:"id"`
	UserName    string       `json:"user_name"`
	FullName    string       `json:"full_name"`
	Email       string       `json:"email"`
	Password    string       `json:"password"`
	CreatedAt   time.Time    `json:"created_at"`
	LastUpdated sql.NullTime `json:"last_updated"`
}

type Workout struct {
	ID            int32  `json:"id"`
	WorkoutName   string `json:"workout_name"`
	WorkoutTypeID string `json:"workout_type_id"`
	UserID        int32  `json:"user_id"`
}

type WorkoutType struct {
	WorkoutType string `json:"workout_type"`
	UserID      int32  `json:"user_id"`
}
