// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	DeleteExercise(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, userName string) error
	DeleteWorkout(ctx context.Context, id int32) error
	DeleteWorkoutJunction(ctx context.Context, arg DeleteWorkoutJunctionParams) error
	GatherExercises(ctx context.Context, userID string) ([]Exercise, error)
	GetExerWorkJunc(ctx context.Context, arg GetExerWorkJuncParams) ([]GetExerWorkJuncRow, error)
	GetUser(ctx context.Context, userName string) (User, error)
	GetWorkoutName(ctx context.Context, arg GetWorkoutNameParams) (Workout, error)
	GetWorkouts(ctx context.Context, userID string) ([]Workout, error)
	InsertNewWorkJunc(ctx context.Context, arg InsertNewWorkJuncParams) error
	RemoveOldWorkJunc(ctx context.Context, arg RemoveOldWorkJuncParams) error
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) error
}

var _ Querier = (*Queries)(nil)
